#pragma once
// GENERATED by tools/burn_table.py on 2026-07-02 — DO NOT EDIT BY HAND.
//   motor: F15 (Estes_F15.eng), 50.4 N*s / 3.45 s
//   mass at descent: 0.950 kg   CdA: 0.0040 m^2
//   ignition delay: 500 ms (command -> thrust)
// Maps descent speed (m/s, downward-positive) to the altitude (m AGL) at
// which the landing-motor fire command must be issued.
namespace burntable {

constexpr float V_MIN = 2.0f;
constexpr float V_STEP = 0.5f;
constexpr int N = 47;

constexpr float H_IGNITE[N] = {
     6.70f,    7.45f,    8.25f,    9.05f,    9.90f,   10.80f,   11.75f,   12.70f,   13.70f,   14.75f,
    15.80f,   16.90f,   18.05f,   19.20f,   20.40f,   21.60f,   22.85f,   24.15f,   25.50f,   26.80f,
    28.15f,   29.55f,   31.00f,   32.45f,   33.90f,   35.40f,   36.95f,   38.50f,   40.05f,   41.60f,
    43.20f,   44.85f,   46.50f,   48.20f,   49.85f,   51.50f,   53.15f,   54.80f,   56.45f,   58.05f,
    59.70f,   61.30f,   62.90f,   64.50f,   66.10f,   67.70f,   69.30f,
};

// Linear interpolation, clamped to the table domain.
inline float hIgnite(float vDown) {
  if (vDown <= V_MIN) return H_IGNITE[0];
  const float idx = (vDown - V_MIN) / V_STEP;
  const int i = (int)idx;
  if (i >= N - 1) return H_IGNITE[N - 1];
  const float f = idx - (float)i;
  return H_IGNITE[i] * (1.0f - f) + H_IGNITE[i + 1] * f;
}

}  // namespace burntable
